### ISSUE TITLE
Provider failed after apply

### ISSUE THREAD

**Issue by hecomp** [lightstep/terraform-provider-lightstep#121]
![Screen Shot 2023-02-07 at 5 40 31 PM](https://user-images.githubusercontent.com/10709807/217383337-4b7c1c7d-e652-4d6b-9c35-7fd6cbb270dd.png)

**Comment by MisterSquishy** [comment]
thanks for the report and sorry for the huge delay here! is this still an issue? we have fixed a host of bugs of this nature in the last several months

**Comment by MisterSquishy** [comment]
closing since we think this has been fixed!
