### ISSUE TITLE
what is the expression for latency and operation rate in lightstep_stream_condition ?

### ISSUE THREAD

**Issue by rohit-dremio** [lightstep/terraform-provider-lightstep#71]
while creating the alert stream we have few signals latency, error percentage and operation rate. For error percentage we do have expression available i.e err  for lightstep_stream_condition.  What is the expression for latency and operation rate in lightstep_stream_condition tf resource.

**Comment by smithclay** [comment]
@rohit-dremio See the examples here for latency, error, and operation rate for `lightstep_stream_condition`: https://github.com/lightstep/terraform-provider-lightstep/blob/main/examples/main.tf#L97-L119

**Comment by rohit-dremio** [comment]
Thank you !!
